### ISSUE TITLE
NT35510_IO_Delay() not found

### ISSUE THREAD

**Issue by Jay-esp** [STMicroelectronics/stm32-nt35510#1]
**Caution**

The Issues are strictly limited for the reporting of problem encountered with the software provided in this project.
For any other problem related to the STM32 product, the performance, the hardware characteristics and boards, the tools the environment in general, please post your report to the **ST Community** in the STM32 MCUs dedicated [page](https://community.st.com/s/topic/0TO0X000000BSqSWAW/stm32-mcus).

**Describe the set-up**

 * The board (either ST RPN reference or your custom board)
 * IDE or at least the compiler and its version

**Describe the bug (skip if none)**

**How to reproduce the bug (skip if none)**

1. Indicate the global behavior of your application project
2. List the modules that you suspect to be the cause of the problem (Drivers, BSP, MW...)
3. Describe the use case that generates the problem
4. How we can reproduce the problem

NT35510_IO_Delay() is not found

**Additional context**

If you have a first analysis, an enhancement, a fix or a patch, thank you to share your proposal.

**Screenshots**

**Comment by TOUNSTM** [comment]
Hello @Jay-esp,

Sorry for the delayed response. Actually you can find this function in this file:
https://github.com/STMicroelectronics/stm32-nt35510/blob/3a64e9bb1c480a833ecbc69d53c0c975f944b50d/nt35510.c#L678-L686

But if you are using this component with the STM32F4/STM32F7 series, you will find this function in BSP boards drivers. As an example, you can refer to this [link](https://github.com/STMicroelectronics/STM32CubeF4/blob/bb621289be5dd54f02e3198e1147b35aed4f7195/Drivers/BSP/STM32469I-Discovery/stm32469i_discovery.c#L924-L927)

Please allow me to close this issue. Thank you for your contribution.

With Regards,
